version: '3.8'

services:
  ghost:
    image: ghost:5-alpine
    container_name: iron-bulwark-ghost
    restart: always
    ports:
      - "2368:2368"
    environment:
      - NODE_ENV=development
      - url=http://localhost:2368
      - database__client=mysql
      - database__connection__host=mysql
      - database__connection__user=ghost
      - database__connection__password=ghost_password
      - database__connection__database=ghost_db
    volumes:
      - ./content:/var/lib/ghost/content
      - ./themes:/var/lib/ghost/content/themes
    depends_on:
      - mysql
    networks:
      - ghost-network

  mysql:
    image: mysql:8.0
    container_name: iron-bulwark-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=ghost_db
      - MYSQL_USER=ghost
      - MYSQL_PASSWORD=ghost_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ghost-network

volumes:
  mysql_data:

networks:
  ghost-network:
    driver: bridge
