version: '3.8'

services:
  ghost:
    image: ghost:5-alpine
    container_name: iron-bulwark-prod
    restart: always
    ports:
      - "2368:2368"
    environment:
      - NODE_ENV=production
      - url=https://your-domain.com
      - database__client=mysql
      - database__connection__host=mysql
      - database__connection__user=ghost_prod
      - database__connection__password=YOUR_STRONG_DB_PASSWORD
      - database__connection__database=ghost_prod_db
      - mail__transport=SMTP
      - mail__options__service=Mailgun
      - mail__options__auth__user=postmaster@your-domain.mailgun.org
      - mail__options__auth__pass=YOUR_MAILGUN_SMTP_PASSWORD
      - mail__options__host=smtp.mailgun.org
      - mail__options__port=587
    volumes:
      - ./content:/var/lib/ghost/content
      - ./themes:/var/lib/ghost/content/themes
    depends_on:
      - mysql
    networks:
      - ghost-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2368"]
      interval: 30s
      timeout: 10s
      retries: 3

  mysql:
    image: mysql:8.0
    container_name: iron-bulwark-mysql-prod
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=YOUR_ROOT_PASSWORD
      - MYSQL_DATABASE=ghost_prod_db
      - MYSQL_USER=ghost_prod
      - MYSQL_PASSWORD=YOUR_STRONG_DB_PASSWORD
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backups:/backups
      - ./scripts/mysql-init:/docker-entrypoint-initdb.d
    networks:
      - ghost-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
    driver: local

networks:
  ghost-network:
    driver: bridge
